server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:8080/user_registration
    username: root
    password: Dat@31102003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true